services:
    - docker

before_install:
    - docker build -t gabrielade/react-test -f ./client/dev.Dockerfile ./client
 
script:
    - docker run -e CI=true gabrielade/react-test npm run test

after_success:
    - docker build -t gabrielade/multi-client ./client
    - docker build -t gabrielade/multi-nginx ./nginx
    - docker build -t gabrielade/multi-server ./server 
    - docker build -t gabrielade/multi-worker ./worker    
    # Login in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Move all this images to docker hub
    - docker push gabrielade/multi-client
    - docker push gabrielade/multi-nginx
    - docker push gabrielade/multi-server
    - docker push gabrielade/multi-worker

deploy:
    # edge: true # forcing Travis to use the v2 (experimental) version of the dpl script which does not have the bug.
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-986991386050"
    bucket_path: "docker-multi"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master    

