services:
    - docker

before_install:
    - docker build -t gabrielade/react-test -f ./client/dev.Dockerfile ./client
 
script:
    - docker run -e CI=true gabrielade/react-test npm run test

after_success:
    - docker build -t gabrielade/multi-client ./client
    - docker build -t gabrielade/multi-nginx ./nginx
    - docker build -t gabrielade/multi-server ./server 
    - docker build -t gabrielade/multi-worker ./worker    
    # Login in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Move all this images to docker hub
    - docker push gabrielade/multi-client
    - docker push gabrielade/multi-nginx
    - docker push gabrielade/multi-server
    - docker push gabrielade/multi-worker

